---
sudo: required
language: python
before_install:
- export PATH=$PATH:/home/travis/PredictionIO/bin
- curl -s https://install.prediction.io/install.sh >install.sh
- bash install.sh -y
- pio-start-all
- pio template get PredictionIO/template-scala-parallel-complementarypurchase MyComplementaryPurchase --name fakeName --package testPackage --email None < answers.txt
- cd MyComplementaryPurchase
- pio app new INVALID_APP_NAME
- pio app list
- pip install predictionio
- python data/import_eventserver.py --access_key 3mZWDzci2D5YsqAnqNnXH9SB6Rg3dsTBs8iHkK6X2i54IQsIZI1eEeQQyMfs7b3F- pio build
- pio train
- pio deploy &
- sleep 120 # let's wait for 2 minutes (dirty hack!)
script:
- curl -v -H "Content-Type:application/json"  -d "{ 'items':[ 's2i1' ], 'num' :3}" http://localhost:8000/queries.json
