---
sudo: required
language: java
before_install:
- export PATH=$PATH:/home/travis/PredictionIO/bin
- curl -s https://install.prediction.io/install.sh >install.sh
- bash -x install.sh -y
- ls -la /home/travis/PredictionIO
- echo $PATH
- pio-start-all
script:
- echo "done"
