---
sudo: required
language: java
before_install:
- export PATH=$PATH:/home/travis/PredictionIO/bin
- curl -s https://install.prediction.io/install.sh >install.sh
- bash install.sh -y
- pio-start-all
- pio template get PredictionIO/template-scala-parallel-complementarypurchase MyComplementaryPurchase --name fakeName --package testPackage --email None < answers.txt
- cd MyComplementaryPurchase
- pio app new INVALID_APP_NAME
- pio app list
- pio build
- pio train
- pio deploy &
- pio app list
script:
- curl -H "Content-Type:application/json"  -d "{ 'items':[ 's2i1' ], 'num' :3}" http://localhost:8000/queries.json
