---
sudo: required
language: java
before_install:
- export PATH=$PATH:/home/travis/PredictionIO/bin
- curl -s https://install.prediction.io/install.sh >install.sh
- bash -c "install.sh -y"
- pio-start-all
- pio template get PredictionIO/template-scala-parallel-complementarypurchase MyComplementaryPurchase
- cd MyComplementaryPurchase
script:
- echo "done"
